live_config_reload = true

[font]
normal = {family = 'GeistMono NF'}
size = 16

[window]
decorations = 'buttonless'
dynamic_padding = false
opacity = 1
padding = { x = 20, y = 15 }
dimensions = { columns = 100, lines = 30 }
option_as_alt = "OnlyLeft"

[cursor]
style ={ shape = 'Underline'}

[colors.primary]
background = "#17191e"
foreground = "#cccccc"

[colors.normal]
white = "#eef0f9"
red = "#dc3657"
green = "#23d18b"
blue = "#2b7eca"
cyan = "#24c0cf"
magenta = "#ad5dca"
yellow = "#ffc368"
black = "#17191e"

[colors.bright]
white = "#fafafa"
red = "#f4587e"
green = "#4bf3c8"
blue = "#54b9ff"
cyan = "#00daef"
magenta = "#cc75f4"
yellow = "#ffd493"
black = "#545864"
